name: Rebuild base Docker image on environment.yml changes

on:
  push:
    branches:
      - main
    paths:
      - environment.yml

jobs:
  rebuild-base-image:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout github actions
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push base image
      run: make rebuild
